### ISSUE TITLE
Support non-root tools version

### ISSUE THREAD

**Issue by tenjaa** [jdx/rtx-action#78]
Hi,

We have a repo that consists of multiple services in need of different tool versions.
Each service has their own folder with an rtx.toml file.

Quickly skimming through the code and looking at the readme, this action only seem to support rtx.toml files from the repo root.

I feel like there could be two options to solve this:

1: An option to pass a `working-directory` from where the config file should be read.

2: Pass a list of directories (or automatically search for all config files), install all versions from them and register the shell hook to be able to switch between multiple services.

Option one would probably be already enough for us but option two sounds a bit fancier.

If you think this is a good idea, I would be willing to try a PR.

**Comment by jdxcode** [comment]
I don’t think we have a good way of accomplishing 2 here. `rtx activate` is not intended to be used (and does not function) in non-interactive contexts. It runs when the prompt is displayed, which never happens if it’s non-interactive.

1 is fine of course though.

**Comment by jdxcode** [comment]
What we could do is use shims to achieve what you’re looking for in 2

**Comment by rdonkin** [comment]
I'd like a similar feature, mostly passing a working directory (option 1) since our actions workflow would build each service (directory) in separate jobs.

I suppose I could write some bash to find the `.tool-versions` file in service directory and pass it in with the `tool-versions:` key.  Or even simpler, just copy the per-service `tool-versions` file to repo root before invoking `jdxcode/rtx-action`.  This will be thrown away at end of job anyway.

**Comment by jdx** [comment]
I mentioned this in another ticket: https://github.com/jdx/rtx/issues/977

but I think rtx itself (not this action) should have some kind of RTX_DIR env var (name is up for discussion) that would use a different directory than cwd for loading `.tool-versions` files. This action could expose a `working_directory` setting that would simply just set that env var.

**Comment by rdonkin** [comment]
Sounds good and I think that an env var would work well - how about `RTX_WORKING_DIR`?

**Comment by jdx** [comment]
I switched this to use shims so this should work now. There is also some config if you want to adjust where `rtx install` takes place.

**Comment by rdonkin** [comment]
For anyone finding this by Google, the new parameter (key) where `rtx install` is run (and hence where `.rtx.toml` or `.tool-versions` are found) is `install_dir`.

This should work for our monorepo use case, thanks @jdx for implementing! 🙌
